# Generated by Django 3.0.2 on 2020-02-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('code', 'name'), ('code',)},
            },
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('weekdays', models.PositiveSmallIntegerField(verbose_name='Días')),
                ('capacity', models.PositiveSmallIntegerField(default=20, verbose_name='Máxima cantidad de estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre'), (3, 'Escuela de Vacaciones de Junio'), (4, 'Escuela de Vacaciones de Diciembre')])),
                ('date_start', models.DateField(verbose_name='Inicio de Semestre')),
                ('date_end', models.DateField(verbose_name='Fin de Semestre')),
                ('assigment_start', models.DateField(verbose_name='Inicio del Periodo de asignación')),
                ('assigment_end', models.DateField(verbose_name='Fin del Periodo de asignación')),
            ],
            options={
                'unique_together': {('year', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='web.Course')),
                ('labschedule', models.ManyToManyField(to='web.LabSchedule')),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='web.Laboratory')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
